FROM node:12.5.0-alpine

ARG WORKDIR
ARG API_URL

ENV HOME=/${WORKDIR} \
  LANG=C.UTF-8 \
  TZ=Asia/Tokyo \
  HOST=0.0.0.0 \
  API_URL=${API_URL}

WORKDIR ${HOME}

COPY package.json .
COPY . .

RUN yarn install

RUN yarn run build

EXPOSE 8080

CMD ["yarn", "start"]
