FROM node:12.5.0-alpine

ARG WORKDIR

ENV HOME=/${WORKDIR}} \
  LANG=C.UTF-8 \
  TZ=Asia/Tokyo \
  HOST=0.0.0.0

WORKDIR ${HOME}

COPY package.json .
COPY . .

RUN apk update && \
  apk upgrade && \
  npm install -g n && \
  yarn install &&\
  rm -rf /var/cache/apk/*

RUN yarn run build

EXPOSE 80

CMD ["yarn", "start"]
