FROM node:12.5.0-alpine

ENV HOME="/sharehack/front" \
  LANG=C.UTF-8 \
  TZ=Asia/Tokyo \
  HOST=0.0.0.0

WORKDIR ${HOME}

COPY package.json .
COPY . .

RUN apk update && \
  apk upgrade && \
  npm install -g n && \
  rm -rf /var/cache/apk/*

RUN yarn install

RUN yarn run build

EXPOSE 8080

CMD ["yarn", "start"]
